/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package ex_json
import java.io.File
import java.io.FileReader
import java.io.FileNotFoundException
import java.util.Scanner
import java.nio.file.*
import kotlinx.serialization.Serializable
import kotlinx.serialization.encodeToString
import kotlinx.serialization.json.Json

class App {
    val greeting: String
        get() {
            return "Hello World!"
        }
}
/* 
fun getText(): String{
    val file = File("./sample.json")
    val scan = Scanner(file)
//    var i = scan.nextLine()
//    i = scan.next()
    print(scan.nextLine())
    print(scan.next())
    return "0"
}
*/

fun getText(): String{
    var str: String = ""
    try{
        val file = File("./sample.json")
        val filereader = FileReader(file)
        var rd: Int = filereader.read()
        while (rd != -1) {
//            print(rd.toChar())
            str += rd.toChar()
            rd = filereader.read()
        }
    }catch (e: FileNotFoundException){
        print(e)
    }
    return str
}

fun main() {
    println(App().greeting)
    println(getText())
}
