/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package ex_json
import java.io.File
import java.io.FileReader
import java.io.FileNotFoundException
import org.json.JSONObject
import com.github.kittinunf.fuel.httpGet
import com.github.kittinunf.result.Result

class App {
    val greeting: String
        get() {
            return "Hello World!"
        }
}

fun getText(): String{
    var str: String = ""
    try{
        val file = File("./sample.json")
        val filereader = FileReader(file)
        var rd: Int = filereader.read()
        while (rd != -1) {
//            print(rd.toChar())
            str += rd.toChar()
            rd = filereader.read()
        }
    }catch (e: FileNotFoundException){
        print(e)
    }
    return str
}

fun main() {
//    println(App().greeting)

    val txt = getText()
    val json: JSONObject = JSONObject(txt)

    val url = json.getString("domain")

    val triple = url.httpGet().response()
    // レスポンスボディを表示
    println(String(triple.second.data))
    println(triple.second.toString())
}